### ISSUE TITLE
Generate enum for all events

### ISSUE THREAD

**Issue by caseypugh** [RoyTheunissen/FMOD-Syntax#11]
## Problem
I'm trying to make a custom Unity component that allows me to pick from a generated AudioEvent in a dropdown and have that save & serialized. 

## Possible solution
It'd be helpful if this plugin could also generate an enum of all the Events too. e.g.
```csharp
public enum AudioEventType {
 MyEvent1,
 MyEvent2
}
```

and then there could be an enum lookup function like 
```csharp
public sealed partial class AudioEvents 
{
   // ...
   public static Find(AudioEveneType eventType) {
       switch (eventType) {
            case AudioEventType.MyEvent1:
               return AudioEvents.MyEvent1;
            case AudioEventType.MyEvent2:
               return AudioEvents.MyEvent2;
              // ... etc
       }
   }
}
```

Or maybe you have a suggested alternative approach. thanks!

**Comment by caseypugh** [comment]
nvm im a dummy and just saw this:
```csharp
[SerializeField] private AudioConfigReference parameterlessAudio;
```

**Comment by RoyTheunissen** [comment]
LOL it's okay, it's a big package, easy to miss stuff.

I appreciate that your first reaction to missing a feature was to try and add it yourself 🙂

**Comment by caseypugh** [comment]
Haha, thanks. However, in a turn of events it doesnt solve my specific use case entirely. Maybe you can lend some advice? 

I'm using another 3rd party plugin, NodeCanvas, which has its own editor renderer for [variables](https://nodecanvas.paradoxnotion.com/documentation/?section=the-blackboard). It only supports standard C# types and adding support for something custom like `AudioReference` is too much work... but if there was an alternative generated `enum` approach that seems like it'd be slightly more flexible of a system. Thoughts?

This is probably more of a NodeCanvas issue than yours so feel free to tell me "not my problem" :)

**Comment by RoyTheunissen** [comment]
> Haha, thanks. However, in a turn of events it doesnt solve my specific use case entirely. Maybe you can lend some advice?
> 
> I'm using another 3rd party plugin, NodeCanvas, which has its own editor renderer for [variables](https://nodecanvas.paradoxnotion.com/documentation/?section=the-blackboard). It only supports standard C# types and adding support for something custom like `AudioReference` is too much work... but if there was an alternative generated `enum` approach that seems like it'd be slightly more flexible of a system. Thoughts?
> 
> This is probably more of a NodeCanvas issue than yours so feel free to tell me "not my problem" :)

Hmm, disappointing to hear that it doesn't "just work" in NodeCanvas. I don't know NodeCanvas but given that `AudioReference` uses a property drawer, it shouldn't be too much work to make it work. You should be able to just draw the property using `EditorGUI.PropertyField` and then it should be displayed exactly the same as in an inspector.

This sounds like less work than making a whole new system just because it's not displayed correctly in NodeCanvas. Also, there's drawbacks to the idea of generating some kind of enum, like it will not handle event renames as gracefully as the current solution, not does it support subfolders.

If you like the idea of the `enum` approach you can try it out of course, but I personally wouldn't go for it.

**Comment by caseypugh** [comment]
Thanks for the reply! I ended up building a [custom editor](https://nodecanvas.paradoxnotion.com/documentation/?section=creating-custom-object-drawers) tool for NodeCanvas. So, all is well. 

I did however have to make my own custom `AudioReference` class that mimics yours but needed to make the the guid public so that it could be serialized by their property drawers.

**Comment by RoyTheunissen** [comment]
> Thanks for the reply! I ended up building a [custom editor](https://nodecanvas.paradoxnotion.com/documentation/?section=creating-custom-object-drawers) tool for NodeCanvas. So, all is well.
> 
> I did however have to make my own custom `AudioReference` class that mimics yours but needed to make the the guid public so that it could be serialized by their property drawers.

Glad to hear!

You can also open a PR where `AudioReference`'s guid is public if that saves you a lot of hassle. It seems like a lot of work to have a whole copy of `AudioReference` 😅
