### ISSUE TITLE
The namespace ... already contains a definition for 'MusicConfig'

### ISSUE THREAD

**Issue by AldeRoberge** [RoyTheunissen/FMOD-Syntax#4]
![image](https://github.com/RoyTheunissen/FMOD-Syntax/assets/4276275/a512776a-6bec-45ab-8233-a8c96d31e218)
Assets\Generated\Scripts\FMOD\FmodEvents.cs(198,18): error CS0101: The namespace 'AGES.FMOD.Generated' already contains a definition for 'MusicConfig'

![image](https://github.com/RoyTheunissen/FMOD-Syntax/assets/4276275/407aacee-7e01-4f5f-b66c-aaa1eb3770e3)

I think it might be due to having events with repeated names : 

![image](https://github.com/RoyTheunissen/FMOD-Syntax/assets/4276275/431eb950-70ff-4f1a-b9ad-d2a6967982a4)

Maybe FMOD-Syntax should take in account the folder when building the names of the sounds?

EnterConfig would become DimensionsDungeonGenericEnter (to match the event : **event:/Dimensions/Dungeon/Generic/Enter**)
EnterConfig would become DimensionsLobbyEnterConfig (to match the event : **event:/Dimensions/Lobby/Enter**)

**Comment by RoyTheunissen** [comment]
The projects I've worked on used unique event names, which besides preventing this exact issue have other advantages such as improved searchability.

Nevertheless, I can understand that if you're adding FMOD-Syntax to an existing project that does not follow this naming convention, it's a difficult transition to make and it would be convenient if there were other options for generated event names.

I'll have a look and see what I can do to ameliorate this issue.

**Comment by RoyTheunissen** [comment]
I have a solution in place, I'm currently exploring ways that I can make the transition easier for people.

**Comment by RoyTheunissen** [comment]
All right, good news! I just released a new version that has the feature you requested.

https://github.com/RoyTheunissen/FMOD-Syntax/releases/tag/v0.1.2

It also comes with a new Auto-Refactoring feature so you'll be able to transition to the requested new syntax format automatically, without anything breaking.

Thanks for using FMOD-Syntax!

**Comment by AldeRoberge** [comment]
Jus tested the latest version, works well! Thank you very much, I'll be recommending this tool to all of my FMOD enabled friends!
